name: hello-world
on:
  pull_request
    branches:
     - 'main'
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Hello World"
        
      - name: step-2
        run: sleep 30
